const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const HIDE_NOTIFICATION_DRAWER = "HIDE_NOTIFICATION_DRAWER";
const DISPLAY_NOTIFICATION_DRAWER = "DISPLAY_NOTIFICATION_DRAWER";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";

module.exports = {
    LOGIN,
    LOGOUT,
    HIDE_NOTIFICATION_DRAWER,
    DISPLAY_NOTIFICATION_DRAWER,
    LOGIN_FAILURE,
    LOGIN_SUCCESS,
}
